// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4TlgAQWaDCDQeUgFzPDxrB9V0bMNf40',
    appId: '1:468896055887:web:6d37d48670d68a5adf203a',
    messagingSenderId: '468896055887',
    projectId: 'whatsapp-backend-8258f',
    authDomain: 'whatsapp-backend-8258f.firebaseapp.com',
    storageBucket: 'whatsapp-backend-8258f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzBpe2n9WoRKIoETJTR1diCYfEjyPgoc8',
    appId: '1:468896055887:android:6e7da1b17ce47f07df203a',
    messagingSenderId: '468896055887',
    projectId: 'whatsapp-backend-8258f',
    storageBucket: 'whatsapp-backend-8258f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCACxTP1dObe-BeIPV4jJ7aaL4sPi2uwrw',
    appId: '1:468896055887:ios:dce56723169a3a08df203a',
    messagingSenderId: '468896055887',
    projectId: 'whatsapp-backend-8258f',
    storageBucket: 'whatsapp-backend-8258f.appspot.com',
    iosClientId: '468896055887-igmfakt29vh3rqj090e6iqvgbu63mt0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCACxTP1dObe-BeIPV4jJ7aaL4sPi2uwrw',
    appId: '1:468896055887:ios:dce56723169a3a08df203a',
    messagingSenderId: '468896055887',
    projectId: 'whatsapp-backend-8258f',
    storageBucket: 'whatsapp-backend-8258f.appspot.com',
    iosClientId: '468896055887-igmfakt29vh3rqj090e6iqvgbu63mt0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
